In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

1.13.1


In [4]:
#Creating Constant in tensorflow

hello = tf.constant("Hello ")
world = tf.constant("World")

In [5]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [6]:
print(hello)

Tensor("Const_2:0", shape=(), dtype=string)


In [8]:
with tf.Session() as sess:
    result = sess.run(hello + world)

In [9]:
print(result)

b'Hello World'


In [10]:
a = tf.constant(10)
b = tf.constant(20)

In [11]:
a + b

<tf.Tensor 'add_2:0' shape=() dtype=int32>

In [12]:
a + b

<tf.Tensor 'add_3:0' shape=() dtype=int32>

In [13]:
a + b

<tf.Tensor 'add_4:0' shape=() dtype=int32>

In [14]:
with tf.Session() as sess:
    result = sess.run(a + b)

In [15]:
result

30

In [16]:
const = tf.constant(10)

In [17]:
fill_mat = tf.fill((4,4),10)

In [18]:
myzeros = tf.zeros((4,4))

In [19]:
myones = tf.ones((4,4))

In [20]:
myrandn = tf.random_normal((4,4),mean=0,stddev=1.0)

In [21]:
myrandu = tf.random_uniform((4,4),minval=0,maxval=1)

In [22]:
myzeros

<tf.Tensor 'zeros:0' shape=(4, 4) dtype=float32>

In [23]:
my_ops = [const,fill_mat,myzeros,myones,myrandn,myrandu]

In [24]:
sess = tf.InteractiveSession()

In [25]:
for op in my_ops:
    print(sess.run(op))
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[ 0.6439151   0.29766932 -0.79691243 -0.540909  ]
 [ 0.04771417  0.39803934  1.2765831   0.12086255]
 [-0.05953497 -0.66936195 -0.10402521  0.46434212]
 [-0.82043815  0.18594062  1.4553843  -0.45705917]]


[[0.8081087  0.3662243  0.58700097 0.31869233]
 [0.08870447 0.30718803 0.25449228 0.6009468 ]
 [0.92298305 0.21325147 0.8058177  0.6620761 ]
 [0.94966495 0.59998465 0.7984941  0.3853122 ]]




In [26]:
for op in my_ops:
    print(op.eval())
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[-0.49092054  0.8248269   0.45703056  0.35494214]
 [-0.00463882 -0.11099474  0.4132867  -0.35659808]
 [-2.2185967   2.1045816   0.57640415 -1.8762552 ]
 [ 1.0994589  -0.53144383  0.66593844  0.2905738 ]]


[[0.0316571  0.2386663  0.7644769  0.5868434 ]
 [0.7804626  0.6791309  0.2802328  0.94924724]
 [0.03259134 0.18312168 0.5303601  0.38028598]
 [0.67277896 0.5678642  0.3515625  0.58947515]]




In [27]:
a = tf.constant([[1,2],
                [3,4]])

In [28]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [29]:
b = tf.constant([[10],[100]])

In [30]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [31]:
result = tf.matmul(a,b)

In [32]:
sess.run(result)

array([[210],
       [430]], dtype=int32)