In [3]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [4]:
dataset = pd.read_csv('Churn_Modelling.csv')

In [5]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [6]:
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:,13].values

In [9]:
X[0]

array([619, 'France', 'Female', 42, 2, 0.0, 1, 1, 1, 101348.88],
      dtype=object)

In [10]:
y[0]

1

In [11]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
labelencoder_X_1 = LabelEncoder()
labelencoder_X_2 = LabelEncoder()

In [12]:
X[:,1] = labelencoder_X_1.fit_transform(X[:,1])
X[:,2] = labelencoder_X_2.fit_transform(X[:,2])

In [13]:
onehotencoder = OneHotEncoder(categorical_features=[1])
X = onehotencoder.fit_transform(X).toarray()
X = X[:,1:]

/Users/rishav/anaconda2/envs/tensorflow_env/lib/python3.6/site-packages/sklearn/preprocessing/_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [14]:
X[0]

array([0.0000000e+00, 0.0000000e+00, 6.1900000e+02, 0.0000000e+00,
       4.2000000e+01, 2.0000000e+00, 0.0000000e+00, 1.0000000e+00,
       1.0000000e+00, 1.0000000e+00, 1.0134888e+05])

In [15]:
from sklearn.model_selection import train_test_split

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [18]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [19]:
import keras

Using TensorFlow backend.


In [20]:
from keras.models import Sequential
from keras.layers import Dense

In [21]:
#Initialising the ANN
classifier = Sequential()

In [22]:
#Adding the input layer and the first hidden layer
classifier.add(Dense(output_dim = 6,init = 'uniform',activation = 'relu', input_dim = 11))

/Users/rishav/anaconda2/envs/tensorflow_env/lib/python3.6/site-packages/ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=11, units=6, kernel_initializer="uniform")`
  


In [23]:
#Adding the secind hidden layer
classifier.add(Dense(output_dim = 6,init = 'uniform',activation = 'relu'))

/Users/rishav/anaconda2/envs/tensorflow_env/lib/python3.6/site-packages/ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  


In [24]:
#Adding the output layer
#If output is 3 then output_dim=3 , activation also we have to change
classifier.add(Dense(output_dim = 1,init = 'uniform',activation = 'sigmoid'))

/Users/rishav/anaconda2/envs/tensorflow_env/lib/python3.6/site-packages/ipykernel_launcher.py:3: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  This is separate from the ipykernel package so we can avoid doing imports until


In [25]:
#Compiling the Ann
classifier.compile(optimizer='adam',loss='binary_crossentropy', metrics = ['accuracy'])

In [26]:
# Fitting thw ANN to the Training set
classifier.fit(X_train,y_train,batch_size=10,nb_epoch=100)

/Users/rishav/anaconda2/envs/tensorflow_env/lib/python3.6/site-packages/ipykernel_launcher.py:2: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  


Epoch 1/100
8000/8000 [==============================] - 1s 156us/step - loss: 0.4922 - acc: 0.7955
Epoch 2/100
8000/8000 [==============================] - 1s 109us/step - loss: 0.4170 - acc: 0.8222
Epoch 3/100
8000/8000 [==============================] - 1s 112us/step - loss: 0.4028 - acc: 0.8292
Epoch 4/100
8000/8000 [==============================] - 1s 109us/step - loss: 0.3917 - acc: 0.8295
Epoch 5/100
8000/8000 [==============================] - 1s 108us/step - loss: 0.3848 - acc: 0.8311
Epoch 6/100
8000/8000 [==============================] - 1s 107us/step - loss: 0.3794 - acc: 0.8309
Epoch 7/100
8000/8000 [==============================] - 1s 111us/step - loss: 0.3758 - acc: 0.8399
Epoch 8/100
8000/8000 [==============================] - 1s 114us/step - loss: 0.3728 - acc: 0.8445
Epoch 9/100
8000/8000 [==============================] - 1s 110us/step - loss: 0.3700 - acc: 0.8464
Epoch 10/100
8000/8000 [==============================] - 1s 106us/step - loss: 0.3683 - acc: 0.8477

8000/8000 [==============================] - 1s 103us/step - loss: 0.3376 - acc: 0.8624
Epoch 83/100
8000/8000 [==============================] - 1s 103us/step - loss: 0.3364 - acc: 0.8627
Epoch 84/100
8000/8000 [==============================] - 1s 103us/step - loss: 0.3373 - acc: 0.8594
Epoch 85/100
8000/8000 [==============================] - 1s 103us/step - loss: 0.3373 - acc: 0.8596
Epoch 86/100
8000/8000 [==============================] - 1s 102us/step - loss: 0.3371 - acc: 0.8615
Epoch 87/100
8000/8000 [==============================] - 1s 103us/step - loss: 0.3372 - acc: 0.8616
Epoch 88/100
8000/8000 [==============================] - 1s 102us/step - loss: 0.3359 - acc: 0.8622
Epoch 89/100
8000/8000 [==============================] - 1s 102us/step - loss: 0.3362 - acc: 0.8622
Epoch 90/100
8000/8000 [==============================] - 1s 102us/step - loss: 0.3361 - acc: 0.8607
Epoch 91/100
8000/8000 [==============================] - 1s 102us/step - loss: 0.3358 - acc: 0.8612
Epo

In [27]:
y_pred = classifier.predict(X_test)

In [29]:
from sklearn.metrics import confusion_matrix,classification_report

In [32]:
y_pred = y_pred > 0.5

In [33]:
confusion_matrix(y_test,y_pred)

array([[1510,   85],
       [ 189,  216]])

In [34]:
classification_report(y_test,y_pred)

'              precision    recall  f1-score   support\n\n           0       0.89      0.95      0.92      1595\n           1       0.72      0.53      0.61       405\n\n   micro avg       0.86      0.86      0.86      2000\n   macro avg       0.80      0.74      0.76      2000\nweighted avg       0.85      0.86      0.86      2000\n'

In [36]:
(1510+216)/2000

0.863